# Generated by Django 6.0.1 on 2026-01-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_web", "0004_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="credential_url",
            field=models.URLField(blank=True),
        ),
    ]
